app:
  version: 0.1.0
server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/conference_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:azerty}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true